import { Separator } from "@/components/ui/separator";

export function Footer() {
  return (
    <footer className="mt-16 py-8">
      <Separator className="mb-6" />
      <div className="text-center space-y-2">
        <p className="text-sm text-muted-foreground">
          This security advisory report was generated by Transilience Security Research Team
        </p>
        <p className="text-xs text-muted-foreground">
          © {new Date().getFullYear()} Transilience. All rights reserved.
        </p>
        <p className="text-xs text-muted-foreground">
          For more information, visit: https://security.transilience.ai
        </p>
      </div>
    </footer>
  );
}